---
title: "Publications"
---

### Detecting disease-critical genes in underrepresented populations

Akamatsu, K., Golzari, S., **Amariuta, T**. Powerful mapping of cis-genetic effects on gene expression across diverse populations reveals novel disease-critical genes. *medRxiv* (2024). [https://www.medrxiv.org/content/10.1101/2024.09.25.24314410v1](https://www.medrxiv.org/content/10.1101/2024.09.25.24314410v1). [https://doi.org/10.1101/2024.09.25.24314410](https://doi.org/10.1101/2024.09.25.24314410).

### Inferring causal cell types in diseases and complex traits

**Amariuta T.**, Siewert-Rocks, K., Price, A.L. Modeling tissue co-regulation estimates tissue-specific contributions to disease. *Nat. Genet*. 55, 1503-1511 (2023). 

### Trans-ancestry portability of genetic association data

**Amariuta, T.**\*, Ishigaki, K.\*, Sugishita, H., Ohta, T., Koido, M., Dey, K. K., Matsuda, K., Murakami, Y., Price, A. L., Kawakami, E., Terao, C. & Raychaudhuri, S. Improving the trans-ancestry portability of polygenic risk scores by prioritizing variants in predicted cell-type-specific regulatory elements. *Nat. Genet*. 52, 1346–1354 (2020). *\* indicates equal contributions*

### Cell-type-specific enhancer predictions

#### Interact with IMPACT on the [UCSC Genome Browser](https://www.amariutalab.org/genomebrowser)

**Amariuta, T.**, Luo, Y., Gazal, S., Davenport, E. E., van de Geijn, B., Ishigaki, K., Westra, H.-J., Teslovich, N., Okada, Y., Yamamoto, K., …, Price, A. L., Raychaudhuri, S. IMPACT: Genomic annotation of cell-state-specific regulatory elements inferred from the epigenome of bound transcription factors. *Am. J. Hum. Genet*. 104, 879–895 (2019).

### Review article on advances in rheumatoid arthritis genetics

**Amariuta, T.**, Luo, Y., Knevel, R., Okada, Y., Raychaudhuri, S. Advances in genetics toward identifying and profiling pathogenic cell states of rheumatoid arthritis. *Immunol. Rev.* (2019).

### A full list of Dr. Amariuta's publications can be found here:

[https://www.ncbi.nlm.nih.gov/myncbi/tiffany.amariuta.1/bibliography/public/](https://www.ncbi.nlm.nih.gov/myncbi/tiffany.amariuta.1/bibliography/public/)
